apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nmbuggy
  template:
    metadata:
      labels:
        app: nmbuggy
    spec:
      containers:
      - name: nmbuggy
        image: 435487142627.dkr.ecr.us-west-2.amazonaws.com/nm
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nmbuggy
    k8s-app: nmbuggy
  name: nmbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: nmbuggy
